### ISSUE TITLE
W4CZ45314 synced but reporting images not available

### ISSUE THREAD

**Issue by TBRC-Travis** [buda-base/public-digital-library#801] opened 2023-02-27 04:21 UTC
@eroux I synced [W4CZ45314](https://library.bdrc.io/show/bdr:W4CZ45314) on Friday but it's still reporting as "images not yet available".

**Comment by eroux** [comment] 2023-02-27 08:06
duplicate of https://github.com/buda-base/archive-ops/issues/866 I think

**Comment by jimk-bdrc** [comment] 2023-02-27 17:30
Same cause, so I'll close this.

**Closed by jimk-bdrc** 2023-02-27 17:30 UTC
