### ISSUE TITLE
Changes to user profile aren't persisting

### ISSUE THREAD

**Issue by TBRC-Travis** [buda-base/public-digital-library#212] opened 2020-08-12 15:56 UTC
Making simple changes to [my profile](https://library.bdrc.io/user) don't seem to stay after the page is reloaded.

For example, after updating my gender:

![profile-edit (1)](https://user-images.githubusercontent.com/19354126/90037961-d085ff80-dc92-11ea-8365-c49b5d7795a0.gif)

Once the update finishes and I reload the profile page my change is gone.

**Comment by eroux** [comment] 2020-08-12 15:59
@MarcAgate can you check the logs to see if it's an error in editserv perhaps? @berger-n can you reproduce it?

**Comment by berger-n** [comment] 2020-08-12 16:58
earlier today I have noticed something like that yes
it needs to be investigated but for now what I've seen is when I save an "other interest" and reload it, it is there, then when I modify my name and then reload, the "other interest" string is empty...
I'm on it

**Comment by berger-n** [comment] 2020-08-12 17:16
I've just created a new user and tried to modify name&gender
server sent back error 500:

![image](https://user-images.githubusercontent.com/33383857/90046028-2a58ea80-dcd0-11ea-845a-7e18a57cbb34.png)
nothing was saved...

**Comment by eroux** [comment] 2020-08-12 17:19
thanks! @MarcAgate can you check the logs and fix the error?

**Comment by MarcAgate** [comment] 2020-08-13 01:36
I created an account using an existing social account and wasn't able to reproduce the issue.

I created an account by providing a username-password combination and did reproduce the issue.

However, I received a confirmation email from auth0, then validated the email of the created account and then I was able to edit and save my profile.

I have to check what it takes to edit a profile and how auth0 is involved in it. At some point, it makes sense to not being able to  edit the profile of an account that is not yet validated. With the same reasoning, it seems weird to be able to use the "not confirmed" account on our site. In general, there is some validation of the account through a valid email address before being able to logged in.

The account used by @berger-n (debug@user.com) is not a valid one and is still pending in auth0 dashboard. I cannot evidently trace what happened in that very case since I can't reproduce the issue without this account password.

As for @TBRC-Travis account, more information is obviously needed about the case (is it a social network account, a user/pass account?, When did the issue occur, just after account creation, 2 days later, etc...)

**Comment by TBRC-Travis** [comment] 2020-08-13 01:49
@MarcAgate I just registered for an account today using the "Sign up with Google" feature and registered with my gmail account (travis@tbrc.org).  The problem occurred just before I submitted this issue.

**Comment by MarcAgate** [comment] 2020-08-13 01:55
@TBRC-Travis . I don't understand since travis@tbrc.org doesn't seem to be a google account.

**Comment by TBRC-Travis** [comment] 2020-08-13 02:14
@MarcAgate it's a google account with a custom domain.  For what it's worth my profile changes are sticking now.  This is not the behavior I was seeing earlier today so something must have changed.  From my perspective this particular issue has now been resolved.  Thank you!

**Comment by eroux** [comment] 2020-08-13 07:48
@MarcAgate I don't think it's linked to the verification of a user/pw account, but even if it was we should accept that some accounts are not checked, because some users won't receive the email, or won't want to click on it, etc. Also, an error 500 is never a good sign, this is clearly a bug in editserv. What does the log say?

**Comment by berger-n** [comment] 2020-08-13 09:12
@MarcAgate you are right it comes from the un/validated email
it worked after I validated the email in auth0 dashboard 
then I deleted account and created it again
same error 500 than yesterday

but client should handle that case better 
(a message like "something went wrong")
I'm on it

**Comment by berger-n** [comment] 2020-08-13 12:37
- I have added an error message when server returns error 500:

![image](https://user-images.githubusercontent.com/33383857/90135014-4c0aae00-dd72-11ea-8b63-33c487c014f2.png)

- I have tried again to create a new user/password and validate email in auth0 dashboard first
yet this time it had no effect and server still returned error 500 when trying to modify data

- there is a slightly different problem when using my real account (valid/created from google account) 
only the latest modification is kept, that is when I modify my genre and reload it has been saved
but when I modify my name then my name is saved but my genre has been reverted to the previous value

**Comment by MarcAgate** [comment] 2020-08-13 14:30
It looks like the issue was a permission issue with local users git repo. @TBRC-Travis I think you can close the issue now.

**Comment by berger-n** [comment] 2020-08-13 14:37
I agree with you @MarcAgate 
everything is working now
thanks

**Closed** 2020-08-14 04:07 UTC
