### ISSUE TITLE
handle transliteration change in etext highlighting

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#343] opened 2020-11-09 15:17 UTC
For instance https://library.bdrc.io/show/bdr:UTIE0OPP000301_v010?startChar=666269&keyword=%22%E0%BD%A6%E0%BE%9F%E0%BD%BC%E0%BD%84%E0%BC%8B%E0%BD%94%E0%BD%A0%E0%BD%B2%E0%BC%8B%E0%BD%84%E0%BD%84%E0%BC%8B%E0%BD%A3%E0%BD%A6%E0%BC%8B%E0%BD%A7%E0%BD%B5%E0%BE%83%E0%BC%8B%E0%BD%A3%E0%BD%A6%E0%BC%8B%E0%BD%96%E0%BE%B1%E0%BD%B4%E0%BD%84%E0%BC%8B%22@bo#open-viewer should have some highlights even when the text is displayed in Wylie

**Comment by berger-n** [comment] 2020-11-10 15:01
it works now:

![image](https://user-images.githubusercontent.com/33383857/98690823-a87b6a80-236d-11eb-8eec-b51feec2f670.png)

![image](https://user-images.githubusercontent.com/33383857/98690863-b3ce9600-236d-11eb-8b31-39c2a2f5a814.png)

that case raises an interesting issue in js with regex in tibetan
སྟོང་པའི་ངང་ལས་ཧཱུྃ་ལས་བྱུང་ won't be found in སྔགས་ཀྱིས་བསང་སྭ་བྷཱ་ཝས་སྦྱང་། སྟོང་པའི་ངང་ལས་ཧཱུྃ་ལས་བྱུང་བའི་སོ་ཤིང་བྱང་ཆུབ་ཤིང་གི་རང་བཞིན་རྩེ་མོ་ལ་སྲད་བུ་དམར་པོ་དང་མེ་ཏོག་གི་ཕྲེང་བ་བཅིངས་པ་དངོས་གྲུབ་ཀྱི་ལྟས་བརྟག་པའི་ནུས་པ་དང་ལྡན་་་་་ (see https://regex101.com/r/ZUkhk7/1/)
problem is with ཧཱུྃ (see https://regex101.com/r/ZUkhk7/2)

**Comment by eroux** [comment] 2020-11-10 15:26
hmm yes, this symbol can be represented in several ways in Unicode... we could make the conversion but let's not do that now. Thanks for that!!

**Comment by berger-n** [comment] 2021-08-24 17:36
seems not to be working when highlighting unicode in unicode: [link](https://library.bdrc.io/show/bdr:UTIE0OPP000301_v010?startChar=666269&keyword=%22%E0%BD%A6%E0%BE%9F%E0%BD%BC%E0%BD%84%E0%BC%8B%E0%BD%94%E0%BD%A0%E0%BD%B2%E0%BC%8B%E0%BD%84%E0%BD%84%E0%BC%8B%E0%BD%A3%E0%BD%A6%E0%BC%8B%E0%BD%A7%E0%BD%B5%E0%BE%83%E0%BC%8B%E0%BD%A3%E0%BD%A6%E0%BC%8B%E0%BD%96%E0%BE%B1%E0%BD%B4%E0%BD%84%E0%BC%8B%22@bo&uilang=bo#open-viewer)

![Screenshot_20210824_193210](https://user-images.githubusercontent.com/33383857/130662822-7d4f495f-27b7-45bd-abbe-acf3d0ac5f9f.png)

---

yet works in the case of AND query: [link](https://library.bdrc.io/show/bdr:UTIE0OPP010417_v037?startChar=337238&keyword=(%22%E0%BD%A3%E0%BE%B7%22%20AND%20%22%E0%BD%96%22%20AND%20%22%E0%BD%9E%E0%BD%B2%22)@bo#open-viewer)

![Screenshot_20210824_193515](https://user-images.githubusercontent.com/33383857/130663241-d4f0cb5e-129f-47f1-b661-2c39c49afd64.png)

**Comment by berger-n** [comment] 2021-08-25 14:58
actually issue was caused by a typo in closing etext button url + this strange ཧཱུྃ character combination
everything seems to be fine now ([wylie](https://library.bdrc.io/show/bdr:UTIE0OPP000301_v010?s=q%3D%2522stong%2520pa%2527i%2520ngang%2520las%2520hU~M%2520las%2520byung%2522~1%26lg%3Dbo-x-ewts%26t%3DEtext%26n%3D1&startChar=248044&keyword=%22stong%20pa%27i%20ngang%20las%20hU~M%20las%20byung%22~1@bo-x-ewts#open-viewer) / [unicode](https://library.bdrc.io/show/bdr:UTIE0OPP000301_v010?s=q%3D%2522%25E0%25BD%25A6%25E0%25BE%259F%25E0%25BD%25BC%25E0%25BD%2584%25E0%25BC%258B%25E0%25BD%2594%25E0%25BD%25A0%25E0%25BD%25B2%25E0%25BC%258B%25E0%25BD%2584%25E0%25BD%2584%25E0%25BC%258B%25E0%25BD%25A3%25E0%25BD%25A6%25E0%25BC%258B%25E0%25BD%25A7%25E0%25BD%25B1%25E0%25BD%25B4%25E0%25BE%2583%25E0%25BC%258B%25E0%25BD%25A3%25E0%25BD%25A6%25E0%25BC%258B%25E0%25BD%2596%25E0%25BE%25B1%25E0%25BD%25B4%25E0%25BD%2584%2522~1%26lg%3Dbo%26t%3DEtext%26n%3D1&startChar=248044&keyword=%22%E0%BD%A6%E0%BE%9F%E0%BD%BC%E0%BD%84%E0%BC%8B%E0%BD%94%E0%BD%A0%E0%BD%B2%E0%BC%8B%E0%BD%84%E0%BD%84%E0%BC%8B%E0%BD%A3%E0%BD%A6%E0%BC%8B%E0%BD%A7%E0%BD%B1%E0%BD%B4%E0%BE%83%E0%BC%8B%E0%BD%A3%E0%BD%A6%E0%BC%8B%E0%BD%96%E0%BE%B1%E0%BD%B4%E0%BD%84%22~1@bo&backToEtext=bdr:UTIE0OPP000301_v010#open-viewer))
closing

**Closed by berger-n** 2021-08-25 14:58 UTC
Labels: bug
