### ISSUE TITLE
mirador not opening the right collection in some cases (?)

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#572] opened 2021-10-01 15:28 UTC
This one is quite bizarre... originally reported by @jimk-bdrc on https://github.com/buda-base/archive-ops/issues/473#issuecomment-932316727 :

going to the viewer on BUDA : https://library.bdrc.io/show/bdr:W00JW501203#open-viewer goes directly to volume 43 and doesn't allow the navigation to other volumes, while when opening in the small viewer app:

https://library.bdrc.io/view/bdr:W00JW501203

it's working fine... @berger-n any idea what's going on?

**Comment by berger-n** [comment] 2021-10-01 15:53
fixed: https://library.bdrc.io/show/bdr:W00JW501203#open-viewer

![Screenshot_20211001_175126](https://user-images.githubusercontent.com/33383857/135650328-1d3d11a9-f523-4e1b-bc67-342c27aabcfd.png)

**Comment by eroux** [comment] 2021-10-03 16:44
thanks! I think there's been perhaps some overcorrection: now https://library.bdrc.io/show/bdr:MW29984_496961#open-viewer opens in a one-volume collection instead of going directly to the volume

**Comment by berger-n** [comment] 2021-10-04 08:20
can't reproduce, neither in Chrome nor Firefox, this is what I see when loading ends: https://library.bdrc.io/show/bdr:MW29984_496961#open-viewer

![Screenshot_20211004_101955](https://user-images.githubusercontent.com/33383857/135817449-6c431bdf-ec8b-4bd1-90af-838149daba7e.png)

**Comment by eroux** [comment] 2021-10-04 08:41
oh, right, sorry, another instance of https://github.com/buda-base/public-digital-library/issues/526

**Comment by berger-n** [comment] 2021-11-19 17:07
something's wrong here, reopening
if I open record https://library.bdrc.io/show/bdr:W00JW501203 and click on image it opens collection view, ok
but if I open viewer https://library.bdrc.io/show/bdr:W00JW501203#open-viewer it seems to randomly open either collection view or a volume, depending on something I don't get...

**Comment by berger-n** [comment] 2021-11-19 18:39
checked links from #572, #578, #585, everything's fine, closing

**Closed by berger-n** 2021-11-19 18:39 UTC
Labels: bug
